### ISSUE TITLE
Can not build module with nw 0.9.x

### ISSUE THREAD

**Issue by ecdeveloper** [nwjs/nw-gyp#29]
The same code which worked fine with node-webkit 0.8.4 now throws errors while building. 

```
../main.cpp:43:31: error: expected class name
class MyClass : node::ObjectWrap {
```

Also, for a regular method setup to exports it throws an error as well:

```
Handle<Value> Method(const Arguments& args) {
    HandleScope scope;
    return scope.Close(String::New("Hey there"));
}
...
exports->Set(String::NewSymbol("Method"), FunctionTemplate::New(Method)->GetFunction());
```

Here is the error: 

```
../main.cpp:300:66: error: cannot initialize a parameter of type 'FunctionCallback' (aka 'void (*)(const FunctionCallbackInfo<v8::Value> &)') with an lvalue of type 'Handle<v8::Value> (const v8::Arguments &)':
      type mismatch at 1st parameter ('const FunctionCallbackInfo<v8::Value> &' vs 'const v8::Arguments &')
        exports->Set(String::NewSymbol("Method"), FunctionTemplate::New(Method)->GetFunction());
```

Once again, this code works just fine with node-webkit 0.8.4 and older.
