### ISSUE TITLE
new failure in 0.49.0

### ISSUE THREAD

**Issue by srguiwiz** [nwjs/nw-gyp#141]
In a project that compiled well at least since 0.47.3 and before, and still compiles with 0.48.4,
now with 0.49.0 we get:

```
In file included from /home/joe/.nw-gyp/0.49.0/src/node.h:67:0,
                 from ../../nan/nan.h:54,
                 from ../src/something.cc:2:
/home/joe/.nw-gyp/0.49.0/deps/v8/include/v8.h: In member function ‘void v8::TracedReferenceBase<T>::SetSlotThreadSafe(T*)’:
/home/joe/.nw-gyp/0.49.0/deps/v8/include/v8.h:912:22: error: expected type-specifier
     reinterpret_cast<std::atomic<T*>*>(&val_)->store(new_val,
                      ^
```
